Fix opam update
Still need to fix on 8.19, 8.20:
 File ./theories/Util/Wf_Uint63/Proofs.v, line 376, characters 4-50:
  Error: Error: Failed to progress.